{{- if or (eq .Values.mode "scalable") .Values.migration.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "krawl.fullname" . }}-mariadb
  labels:
    {{- include "krawl.labels" . | nindent 4 }}
type: Opaque
stringData:
  mariadb-password: {{ .Values.mariadb.password | quote }}
  {{- if .Values.mariadb.enabled }}
  mariadb-root-password: {{ .Values.mariadb.rootPassword | quote }}
  {{- end }}
---
{{- if .Values.redis.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "krawl.fullname" . }}-redis
  labels:
    {{- include "krawl.labels" . | nindent 4 }}
type: Opaque
stringData:
  redis-password: {{ .Values.redis.password | quote }}
{{- end }}
{{- end }}
